#! /usr/bin/env bash

# Drupal drush database backup
# Arguments:
# - Container name
# - Destination path
drush () {
  container=$1
  destination=$2

  drush_path=$(get_container_label "${container}" "com.defcomsoftware.backup.drush.path")
  if [ -z "$drush_path" ]; then
    echo_verbose "## No drush path defined. Skipping..."
    return
  fi

  docker exec "${container}" "$drush_path" sql-dump > "${destination}.sql"

  post_backup "${destination}.sql"
}
