#! /usr/bin/env bash

# Generic files backup
files () {
  type="files"
  containers=$(docker ps --filter="label=defcomsoftware.backup.type=${type}" --format "{{.Names}}")
  if [ ! -n "$containers" ]; then
    echo "No containers for type ${type}."
  fi

  for container in ${containers}; do
    echo "Creating files dump for ${container}."
    destination=${backups_route}/$(docker inspect -f '{{ index .Config.Labels "defcomsoftware.backup.destination"}}' ${container})
    mkdir -p ${destination}
    source=$(docker inspect -f '{{ index .Config.Labels "defcomsoftware.backup.source"}}' ${container})
    if [ -z $source ]; then
      (( $debug )) && echo "-No source path defined. Skipping."
      continue
    fi

    docker cp ${container}:${source} ${destination}/${container}_${date}

    post_backup ${destination}/${container}_${date}
  done
}
