#! /usr/bin/env bash

# Generic files backup
# Arguments:
# - Container name
# - Destination path
files () {
  container=$1
  destination=$2

  source=$(get_container_label "${container}" "com.defcomsoftware.backup.files.source")
  if [ -z "$source" ]; then
    echo_verbose "## No source path defined. Skipping..."
    return
  fi

  docker cp "${container}:${source}" "${destination}"

  post_backup "${destination}"
}
