#! /usr/bin/env bash

# Generic MySQL/MariaDB backup
# Arguments:
# - Container name
# - Destination path
mysql () {
  container=$1
  destination=$2

  user=$(get_env_from_container "${container}" MYSQL_USER)
  database=$(get_env_from_container "${container}" MYSQL_DATABASE)
  docker exec "${container}" mysqldump -u "$user" "${database}" > "${destination}.sql"

  post_backup "${destination}.sql"
}
