#! /usr/bin/env bash

# Generic PostgreSQL backup
# Arguments:
# - Container name
# - Destination path
postgresql () {
  container=$1
  destination=$2

  user=$(get_env_from_container "${container}" POSTGRES_USER)
  database=$(get_env_from_container "${container}" POSTGRES_DB)
  docker exec --user "${user:=postgres}" "${container}" pg_dump "$database" > "${destination}.sql"

  post_backup "${destination}.sql"
}
